### ISSUE TITLE
mutes module doesn't handle not having permissions

### ISSUE THREAD

**Issue by tadeokondrak** [nixnest/scepter#7]
(node:27986) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
    at item.request.gen.end (/home/tdeo/scepter/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:79:15)
    at then (/home/tdeo/scepter/node_modules/snekfetch/src/index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:27986) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:27986) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ldelelis** [comment]
If I understand this correctly, this was fixed in #11, having implemented correct handling of async methods. Right now it logs `WARNING: 'mute <@126860967865745409>' errored with 'DiscordAPIError: Missing Access'`. Should we set a more "user friendly" error for this?
